name: terraform destroy
'on':
  workflow_dispatch:
jobs:

  tf-destroy:
    name: tf-destroy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      id-token: write
      packages: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        # Update the values with the output from the setup step
        with:
            workload_identity_provider: projects/225327824991/locations/global/workloadIdentityPools/automation-wif-pool/providers/github
                                        #projects/203546026970/locations/global/workloadIdentityPools/github-jomcyg/providers/github
            service_account: sa-lzguardrails@jmc-central-pj.iam.gserviceaccount.com
                        #sa-jomcyggithub-gcloudauth@jmc-devsecops.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.4

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2' #@v2.1.0
        with:
          version: '>= 475.0.0'
      - name:  destroy
        id: destroy
        run: |
              pwd && ls 
              terraform init -backend-config="bucket=jmcorg-tfstate_lz"
              terraform destroy -auto-approve
              terraform state rm -force-unlock $(terraform state list)